### PR TITLE
Update config

### PR DESCRIPTION
**Pull request by nr23730**
- Use OncoKB API that serves therapy recommendations using token
- Enable quick search via env file

### CODE REVIEW

**Comment by Unberath** [comment]
Quick search works like a charm, but the OncoKB change only works (meaning the patient view doesn't load) if the token is set, whereas it has worked before either way. Is this expected behavior?

Error from portal:
`{"req":{"method":"POST","url":"http://131.188.43.108:8080/proxy/oncokb/annotate/mutations/byProteinChange","data":[{"id":"Testpatient_01-&-MSIH","alteration":"MSI-H","gene":{"hugoSymbol":"Other Biomarkers"},"tumorType":"Breast Carcinoma"},{"id":"Testpatient_02-&-MSIH","alteration":"MSI-H","gene":{"hugoSymbol":"Other Biomarkers"},"tumorType":"Breast Carcinoma"},{"id":"Testpatient_01-&-TMBI","alteration":"TMB-H","gene":{"hugoSymbol":"Other Biomarkers"},"tumorType":"Breast Carcinoma"},{"id":"Testpatient_02-&-TMBI","alteration":"TMB-H","gene":{"hugoSymbol":"Other Biomarkers"},"tumorType":"Breast Carcinoma"}],"headers":{"accept":"application/json","content-type":"application/json"}},"xhr":{},"text":"<!doctype html><html lang=\"en\"><head><title>HTTP Status 500 – Internal Server Error</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class=\"line\" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Request processing failed; nested exception is org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]\n\torg.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\torg.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\n\tjavax.servlet.http.HttpServlet.service(HttpServlet.java:652)\n\torg.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n\tjavax.servlet.http.HttpServlet.service(HttpServlet.java:733)\n\torg.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\torg.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)\n\torg.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)\n\torg.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)\n\torg.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)\n\torg.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)\n\torg.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)\n\torg.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)\n\torg.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)\n\tcom.vlkan.hrrs.servlet.HrrsFilter.doFilter(HrrsFilter.java:85)\n\torg.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)\n\torg.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)\n\torg.mskcc.cbio.portal.util.RequestBodyGZipFilter.doFilter(RequestBodyGZipFilter.java:72)\n\torg.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)\n\torg.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)\n</pre><p><b>Root Cause</b></p><pre>org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]\n\torg.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)\n\torg.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170)\n\torg.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112)\n\torg.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\torg.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)\n\torg.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)\n\torg.springframework.web.client.RestTemplate.execute(RestTemplate.java:714)\n\torg.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)\n\torg.cbioportal.proxy.ProxyController.exchangeData(ProxyController.java:95)\n\torg.cbioportal.proxy.ProxyController.proxyOncokb(ProxyController.java:66)\n\tjdk.internal.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)\n\tjava.base&#47;jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tjava.base&#47;java.lang.reflect.Method.invoke(Method.java:566)\n\torg.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)\n\torg.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)\n\torg.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)\n\torg.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)\n\torg.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)\n\torg.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\torg.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)\n\torg.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)\n\torg.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\torg.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\n\tjavax.servlet.http.HttpServlet.service(HttpServlet.java:652)\n\torg.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n\tjavax.servlet.http.HttpServlet.service(HttpServlet.java:733)\n\torg.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\torg.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)\n\torg.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)\n\torg.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)\n\torg.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)\n\torg.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)\n\torg.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\torg.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)\n\torg.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)\n\torg.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)\n\torg.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)\n\tcom.vlkan.hrrs.servlet.HrrsFilter.doFilter(HrrsFilter.java:85)\n\torg.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)\n\torg.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)\n\torg.mskcc.cbio.portal.util.RequestBodyGZipFilter.doFilter(RequestBodyGZipFilter.java:72)\n\torg.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)\n\torg.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)\n</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.61</h3></body></html>","statusText":"","statusCode":500,"status":500,"statusType":5,"info":false,"ok":false,"redirect":false,"clientError":false,"serverError":true,"error":{"status":500,"method":"POST","url":"http://131.188.43.108:8080/proxy/oncokb/annotate/mutations/byProteinChange"},"created":false,"accepted":false,"noContent":false,"badRequest":false,"unauthorized":false,"notAcceptable":false,"forbidden":false,"notFound":false,"unprocessableEntity":false,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"total-count,sample-count","cache-control":"no-cache, no-store, max-age=0, must-revalidate","connection":"keep-alive","content-encoding":"gzip","content-language":"en","content-type":"text/html;charset=utf-8","date":"Wed, 27 Jan 2021 15:34:37 GMT","expires":"0","pragma":"no-cache","server":"nginx/1.18.0","transfer-encoding":"chunked","vary":"accept-encoding","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block"},"header":{"access-control-allow-origin":"*","access-control-expose-headers":"total-count,sample-count","cache-control":"no-cache, no-store, max-age=0, must-revalidate","connection":"keep-alive","content-encoding":"gzip","content-language":"en","content-type":"text/html;charset=utf-8","date":"Wed, 27 Jan 2021 15:34:37 GMT","expires":"0","pragma":"no-cache","server":"nginx/1.18.0","transfer-encoding":"chunked","vary":"accept-encoding","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block"},"type":"text/html","charset":"utf-8","links":{},"body":null,"url":"http://131.188.43.108:8080/patient?studyId=testpatient&caseId=Testpatient"}`

Error in logs:
`cbioportal_container           | Jan 27, 2021 3:34:37 PM org.apache.catalina.core.StandardWrapperValve invoke
cbioportal_container           | SEVERE: Servlet.service() for servlet [proxy] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]] with root cause
cbioportal_container           | org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
cbioportal_container           |        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
cbioportal_container           |        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170)
cbioportal_container           |        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112)
cbioportal_container           |        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
cbioportal_container           |        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
cbioportal_container           |        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
cbioportal_container           |        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:714)
cbioportal_container           |        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)
cbioportal_container           |        at org.cbioportal.proxy.ProxyController.exchangeData(ProxyController.java:95)
cbioportal_container           |        at org.cbioportal.proxy.ProxyController.proxyOncokb(ProxyController.java:66)
cbioportal_container           |        at jdk.internal.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
cbioportal_container           |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cbioportal_container           |        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
cbioportal_container           |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
cbioportal_container           |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
cbioportal_container           |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
cbioportal_container           |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
cbioportal_container           |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
cbioportal_container           |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
cbioportal_container           |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
cbioportal_container           |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
cbioportal_container           |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
cbioportal_container           |        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
cbioportal_container           |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
cbioportal_container           |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
cbioportal_container           |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at org.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
cbioportal_container           |        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
cbioportal_container           |        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
cbioportal_container           |        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
cbioportal_container           |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
cbioportal_container           |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
cbioportal_container           |        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
cbioportal_container           |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
cbioportal_container           |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at com.vlkan.hrrs.servlet.HrrsFilter.doFilter(HrrsFilter.java:85)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
cbioportal_container           |        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at org.mskcc.cbio.portal.util.RequestBodyGZipFilter.doFilter(RequestBodyGZipFilter.java:72)
cbioportal_container           |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
cbioportal_container           |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cbioportal_container           |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cbioportal_container           |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
cbioportal_container           |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
cbioportal_container           |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
cbioportal_container           |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
cbioportal_container           |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
cbioportal_container           |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
cbioportal_container           |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
cbioportal_container           |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
cbioportal_container           |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
cbioportal_container           |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
cbioportal_container           |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
cbioportal_container           |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
cbioportal_container           |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
cbioportal_container           |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cbioportal_container           |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
cbioportal_container           |        at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by nr23730** [comment]
I know, the error handling from cBioPortal is "not perfect". 😔
On the other side our installation instruction clearly tell to obtain a token for OncoKB. 

But you're right. Maybe it's better to set the url via the .env file. Then we could instruct the users to uncomment that url when they enter an OncoKB token.

**Comment by Unberath** [comment]
> I know, the error handling from cBioPortal is "not perfect". 😔
> On the other side our installation instruction clearly tell to obtain a token for OncoKB.

I'm fine with the change if this is kind of expected behavior and not a fault on our side.
 
> But you're right. Maybe it's better to set the url via the .env file. Then we could instruct the users to uncomment that url when they enter an OncoKB token.

Probably a matter of taste, both versions are not perfect as cBioPortal simply could do a better job at error handling.

**Review by Unberath — APPROVED** [review]

**Comment by nr23730** [comment]
I think it with 962807f I made some sort of compromise. Now it would also be possible to use cBioPortal without OncoKB token but still get valuable information from it.

**Review by Unberath — APPROVED** [review]
Thanks! 
lgtm

**Pull request merged**
