### PR TITLE
Replace genomenexus-vep with ensembl-rest

### LINKED ISSUE #22: Complete offline-mode for genomenexus

### PR DESCRIPTION
**Pull request by nr23730**
fixes #22 in most parts.

Genomenexus-VEP sometimes causes problems because it's just a wrapper and does not offer the full functionality. 
In combination with a offline-import of mutation assessor it is indeed possible to run a full offline version of genome nexus.

Also: Fixes CI. There is no point in building the genome-nexus-db every time as it is pulled form Docker Hub either way.

EDIT: This requires two new images that are currently being pushed to the docker harbor.
Also: Our Docker harbor changed it's name from docker.miracum.org to harbor.miracum.org. This is especially important when pushing new images.

### CODE REVIEW

**Comment by Unberath** [comment]
This is still blocked by your upload issues with harbor, right?

**Comment by nr23730** [comment]
> This is still blocked by your upload issues with harbor, right?

Somewhat yes. Of course the mysql-image could be built locally but it would be good if it's available on the harbor as well.

**Comment by Unberath** [comment]
If there weren't the problems with our docker harbor, this PR lgtm

**Comment by nr23730** [comment]
Changed this the way we discussed via mail. Also changed CI so that only cBioPortal and the nginx container will be rebuilt as these are the only components not covered by CI before. However, the docker-compose syntax is checked anyway.

**Review by Unberath — APPROVED** [review]
Thanks, lgtm!
I had some issues, but that's only because I constantly ran out of disk space. We should probably put some estimate somewhere how much disk space is needed for the whole installation.

**Pull request merged**
