### PR TITLE
don't skip loh mutations on import

### PR DESCRIPTION
**Pull request by nr23730**
This is intended to work together with nr23730/cbioportal-frontend#60.
The change will be effective for all new imported data as before LoH was skipped during the import process.

### CODE REVIEW

**Comment by Unberath** [comment]
@nr23730  I still have some problems getting this to work as your changes don't show even in a fresh built version of this branch. Is this a problem on my end? Are you certain that the replacements do work?

**Comment by nr23730** [comment]
You need to build this with the `loh` frontend branch, deploy it and then import a study containing an LoH mutation (Patient_example contains a LoH Mutation in FOXJ2!). Then you'll see the `L` in the MS (Mutation Status) column, which is now enabled by default.
And yes, I can confirm that the replacements do work.

**Comment by Unberath** [comment]
Finally got it to work, and your replacements work like a charm!
I was a bit confused because I got an error:3 after the importer validated the files successfully without importing (so with warnings and without -o flag). 
Did you also get the error? We could merge anyway because the solution works nevertheless IMO.

**Comment by nr23730** [comment]
Closing this as this was already part of the 3.7.20 update.

**Pull request closed without merging**
