### PR TITLE
enhance testpatient

### PR DESCRIPTION
**Pull request by nr23730**
This PR adresses two points:

1. Add some additional clinical attributes
2. Change some attributes to according to the "guidelines" of cBioPortal. Attributes like `GENDER`, `AGE` or `PATIENT_DISPLAY_NAME` will be shown in the headblock above the tabs.

### CODE REVIEW

**Comment by Unberath** [comment]
> 1. Add some additional clinical attributes

Are those just kind of random example attributes or should they be displayed in any special way?

> 2. Change some attributes to according to the "guidelines" of cBioPortal. Attributes like `GENDER`, `AGE` or `PATIENT_DISPLAY_NAME` will be shown in the headblock above the tabs.

Good addition!
I'm not that happy with the age instead of birthdate in the clinical setting (may be outdated, additional identification based on the birthdate), but for our example patient we can change this to the compliant and out of the box working format.

**Comment by nr23730** [comment]
The additional attributes are all part of the ZPM dataset and can be part of the molecular diagnostics. Despite from the MSI and TMB they are not displayed in a special way. I think it would be nice to have a few of these for demonstration purposes as they make much more sense for an attribute to be selected in a therapy recommendation than the ones present now.

For the birthdate/age thing I definitely see your point and it won't stop us from providing the birthdate as well. I see this more from a standpoint that it represents the state when the patient is being presented and gets a therapy recommendation. 
Other attributes like `OS_STATUS`, `OS_MONTHS` `DFS_STATUS` or `DFS_MONTHS` may also be outdated / require regularly updates.

**Comment by nr23730** [comment]
Also John Doe is unlikely to have breast cancer. 🙈

**Review by Unberath — APPROVED** [review]
Good addition for our sample patient!

**Pull request merged**
